[msg P3PHealWelcome]
[f 0 8 65278][f 1 31][f 2 2 65535 65535][f 2 3 65535 0]Welcome to P3P Inspired Healing![f 0 4][e]
[f 0 8 65278][f 1 31][f 2 2 65535 65535][f 2 3 65535 0]This mod has two different modes. The first makes the[n]mod apply throughout the entire game.[n]The other makes the mod wait until later in the to apply.[n]Late game is the recommended mode.[f 0 4][e]

[msg P3PChooseVersion]
[f 0 8 -258][f 1 31]> Which version would you like to use?[e]

[sel P3PHealVersionSel]
[f 0 8 -258][f 1 31]Full Game[e]
[f 0 8 -258][f 1 31]Late Game[e]

[msg P3PHealTutorial]
[f 0 8 65278][f 1 31][f 2 2 65535 65535][f 2 3 65535 0]P3P Inspired Healing is now enabled![f 0 4][e]
[f 0 8 65278][f 1 31][f 2 2 65535 65535][f 2 3 65535 0]From this point on, characters will not automatically[n]heal when returning to the lobby.[f 0 4][e]
[f 0 8 65278][f 1 31][f 2 2 65535 65535][f 2 3 65535 0]In order to heal, you will need to interact with the[n]clock and supply yen.[f 0 4][e]
[f 0 8 65278][f 1 31][f 2 2 65535 65535][f 2 3 65535 0]IF you return to the lobby while one of your party is[n]at 0 HP, then you will be prompted to pay a penalty to heal[n]them. If you choose not to, then they will return to the dorm.[f 0 4][e]

[msg P3PHealDead]
[f 0 8 -258][f 1 31]One or more of your party members are unconcious.[f 0 4][e]
[f 0 8 -258][f 1 31]> Would you like to heal them for 2500 yen?[e]

[sel P3PHealDeadSel]
[f 0 8 -258][f 1 31]Yes[e]
[f 0 8 -258][f 1 31]No[e]

[msg P3PHealClock]
[f 0 8 -258][f 1 31]> Would you like to heal or save?[e]

[sel P3PHealClockSel]
[f 0 8 -258][f 1 31]Heal[e]
[f 0 8 -258][f 1 31]Save[e]

[msg P3PHealingMenu]
[f 0 8 -258][f 1 31]Healing will cost 2000 yen.[f 0 4][e]
[f 0 8 -258][f 1 31]> Would you like to heal?[e]

[sel P3PHealingMenuSel]
[f 0 8 -258][f 1 31]Yes[e]
[f 0 8 -258][f 1 31]No[e]

[msg Broke]
[f 0 8 -258][f 1 31]You do not have enough yen.[f 0 4][e]